# Version controlled for example purposes only. You could have this file
# be created by developers and override any other configuration.

name: nestjs-example-development

database:
  host: localhost
  port: 5432
  database: development
  password: development
