name: docs

on:
  push:
    branches:
      - main

# https://vuepress.github.io/guide/deployment.html#github-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v1

      - run: npm ci
        working-directory: ./docs
      - run: npm run build
        working-directory: ./docs
        env:
          NODE_ENV: production

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs/src/.vuepress/dist
          enable_jekyll: false
