name: docs

on:
  push:
    branches:
      - main

# https://vuepress.github.io/guide/deployment.html#github-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: "bun install --frozen-lockfile"
      - run: "bun run docs:build"
        env:
          NODE_ENV: production

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/.vitepress/dist
          enable_jekyll: false
