name: docs

on:
  push:
    branches:
      - main

jobs:
  # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - run: node common/scripts/install-run-rush.js install
      # Make sure to build all dependant packages so typings are in place
      - run: node common/scripts/install-run-rush.js build --verbose

      - run: npm ci
        working-directory: ./docs
      - run: npm run build
        working-directory: ./docs

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs/build
          enable_jekyll: false
