name: docs

on:
  push:
    branches:
      - main

jobs:
  # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./docs/build
          enable_jekyll: false
