name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: "ci"

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12, 14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --global yarn
      - run: docker-compose up -d --build
      - run: yarn install
      # Make sure to build all dependant packages so typings are in place
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test:cov
        env:
          # node-vault will read from this environment variable if set
          # https://github.com/kr1sp1n/node-vault/blob/0fa666afb9da14f25cf054e195c18b5a560fcaed/src/index.js#L68
          VAULT_ADDR: "http://localhost:8200"
