name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/changesets/changesets/issues/517#issuecomment-1182094769
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - run: docker-compose up -d --build

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: "pnpm install --frozen-lockfile"
      - run: "pnpm run checkstyle"
      - run: "pnpm run build"
      - run: "pnpm run lint"
      - run: "pnpm run test:coverage"
        env:
          # node-vault will read from this environment variable if set
          # https://github.com/kr1sp1n/node-vault/blob/0fa666afb9da14f25cf054e195c18b5a560fcaed/src/index.js#L68
          VAULT_ADDR: "http://localhost:8200"
      # - run: "pnpm run changeset:status"
