name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: "ci"

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12, 14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker-compose up -d --build
      - run: node common/scripts/install-run-rush.js install
      # Make sure to build all dependant packages so typings are in place
      - run: node common/scripts/install-run-rush.js build --verbose
      - run: node common/scripts/install-run-rush.js lint --verbose
      - run: node common/scripts/install-run-rush.js test:cov --verbose
        env:
          # node-vault will read from this environment variable if set
          # https://github.com/kr1sp1n/node-vault/blob/0fa666afb9da14f25cf054e195c18b5a560fcaed/src/index.js#L68
          VAULT_ADDR: "http://localhost:8200"

  publish:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js build --verbose
      - run: node common/scripts/install-run-rush.js publish --apply --target-branch main --publish --set-access-level public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
