name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/changesets/changesets/issues/517#issuecomment-1182094769
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: docker compose up -d --build --wait
      - run: "bun install --frozen-lockfile"
      - run: "bun run checkstyle"
      - run: "bun run build"
      - run: "bun run lint"
      - run: "bun run test:coverage"
        env:
          # node-vault will read from this environment variable if set
          # https://github.com/kr1sp1n/node-vault/blob/0fa666afb9da14f25cf054e195c18b5a560fcaed/src/index.js#L68
          VAULT_ADDR: "http://localhost:8200"
